name 'java-service'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Library cookbook which provides resources for configuring a Java service.'
long_description 'Library cookbook which provides resources for configuring a Java service.'
version '1.0.0'

supports 'centos'
supports 'redhat'
supports 'ubuntu'

depends 'apt'
depends 'java'
depends 'maven', '~> 2.0'
depends 'poise', '~> 2.2'
depends 'poise-service', '~> 1.0'
