name 'java-service'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Library cookbook which provides resources for configuring a Java service.'
long_description 'Library cookbook which provides resources for configuring a Java service.'
version '1.2.0'

supports 'centos', '>= 6.4'
supports 'redhat', '>= 6.4'
supports 'ubuntu', '>= 12.04'

depends 'apt', '~> 2.9'
depends 'java', '~> 1.39'
depends 'libarchive', '~> 0.6'
depends 'poise', '~> 2.2'
depends 'poise-service', '~> 1.0'
depends 'rc', '~> 1.5'
depends 'yum-centos', '~> 0.4'
depends 'yum-epel', '~> 0.6'
